### ISSUE TITLE
Python bindings broken

### ISSUE THREAD

**Issue by bmihaila** [googleprojectzero/functionsimsearch#12]
Compiled everything in the docker way and code runs. Building the python bindings and then trying to run some code that needs them, breaks though. 

Step to repro:
build python bindings as described in README:
```
root@6770c506c67a:/code/functionsimsearch# python3 ./setup.py install --user
running install
running build
running build_ext
building 'functionsimsearch' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/disassembly
creating build/temp.linux-x86_64-3.6/searchbackend
creating build/temp.linux-x86_64-3.6/util
creating build/temp.linux-x86_64-3.6/pybindings
...
```
then try to run some python code gives the error:
```
root@6770c506c67a:/code/functionsimsearch/pybindings# python3 pybindings_test.py
Traceback (most recent call last):
  File "pybindings_test.py", line 1, in <module>
    import functionsimsearch, unittest
ImportError: /root/.local/lib/python3.6/site-packages/functionsimsearch.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Z26ExtractImmediateFromStringRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPSt6vectorImSaImEE
root@6770c506c67a:/code/functionsimsearch/pybindings# python pybindings_test.py
Traceback (most recent call last):
  File "pybindings_test.py", line 1, in <module>
    import functionsimsearch, unittest
ImportError: /root/.local/lib/python2.7/site-packages/functionsimsearch.so: undefined symbol: _Z26ExtractImmediateFromStringRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPSt6vectorImSaImEE
```

**Comment by thomasdullien** [comment]
Hey there,

I had forgotten to add disassembly/extractimmediate.cpp to the setup.py
file, this
should be fixed now. You will probably have to clean / remove your old
build files.

Cheers,
Thomas

Am Mo., 29. Okt. 2018 um 11:54 Uhr schrieb Bogdan Mihaila <
notifications@github.com>:
